name: Build wiki

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main.py
        run: |
          python main.py

      - name: Create gh-pages branch and push if it doesn't exist
        run: |
          git branch | grep gh-pages || git checkout -b gh-pages && git push origin gh-pages

      - name: Deploy to gh-pages
        if: success()
        run: |
          git config --global user.name 'SimpleGitDocs'
          git config --global user.email 'SimpleGitDocs@example.com'
          git clone --branch gh-pages https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages
          rm -rf gh-pages/*
          cp -r ./temp/* ./gh-pages/
          cd gh-pages
          git add .
          git commit -m 'Deploy to gh-pages'
          git push origin gh-pages --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}